### ISSUE TITLE
react-native-dom

### ISSUE THREAD

**Issue by Hermanya** [lelandrichardson/react-primitives#107]
Today I stumbled upon react-native-dom. 
Supposedly, it's an alternative to react-native-web 
I created this thread, to get clarification on the difference between the two libs: https://github.com/vincentriemer/react-native-dom/issues/17

It looks quite interesting, perhaps react-primitives should consider a future migration from react-native-web, once react-native-dom becomes less experimental.

**Comment by thebetterjort** [comment]
https://github.com/vincentriemer/react-native-dom/issues/17
