### ISSUE TITLE
Support for latest react-web-native

### ISSUE THREAD

**Issue by jcampbell05** [lelandrichardson/react-primitives#109]
Is it possible to support the latest react-web-native, this has bug fixes that resolve issues in older browsers.

**Comment by mathieudutour** [comment]
Can you create a PR? Happy to merge it

**Comment by necolas** [comment]
I think you're better off aliasing package names than using this package. It's out of date and the exported API is not compatible with the rest of the React Native ecosystem

**Comment by mathieudutour** [comment]
wait you meant `react-native-web` right?

**Comment by jcampbell05** [comment]
Yes I did, I've tried to update it using a branch but it breaks.

**Comment by zephraph** [comment]
> I think you're better off aliasing package names than using this package. It's out of date and the exported API is not compatible with the rest of the React Native ecosystem

@necolas What do you mean by that exactly? `react-native-web` is out of date? Or this package?

**Comment by jcampbell05** [comment]
This package is out of date, it uses an old version of the native-web package. I tried upgrading the version and using the new StyleManager class but it's a non trivial change as things like transform is broken
