### ISSUE TITLE
Use of normal CSS or JSS ?

### ISSUE THREAD

**Issue by davidjtorres** [lelandrichardson/react-primitives#122]
Is it possible to normal CSS on react-native-web using standard HTML dom elements ?
and use a different instead of Flex ?

**Comment by haf** [comment]
Curious too; specifically with emotion.sh

**Comment by mathieudutour** [comment]
emotion has a @emotion/primitives package: https://emotion.sh/docs/@emotion/primitives

But no, you can't use normal CSS as it would defeat the point of `react-primitives` (eg. be able to use components across platforms)
