### ISSUE TITLE
add node-webrender

### ISSUE THREAD

**Issue by cztomsik** [lelandrichardson/react-primitives#128]
Hey, I'd like to add support for [node-webrender](https://tomsik.cz/node-webrender) (mostly because I would then get support for `styled-components` for free) but it's not clear to me how does this actually work (it seems to always require `react-native-web`)

Also, how is this related to `react-platform`? Is it already available anywhere? I couldn't find it, so I'm filing it here.

And lastly, it probably misses few very useful things like `TextInput` and `ScrollView` - do you plan to add any of these in the future?

**Comment by mathieudutour** [comment]
I'm not sure what's `node-webrender` (link to a 404) or `react-platform` sorry

**Comment by cztomsik** [comment]
sorry, it was renamed to `stain`
https://tomsik.cz/stain/

**Comment by mathieudutour** [comment]
Still not sure what it is. The documentation has 404 links everywhere and there is no API reference.

So I'm going to close this as it doesn't look mature enough to be included here
