### ISSUE TITLE
lint error in src/injection/react-native-web.js

### ISSUE THREAD

**Issue by brodybits** [lelandrichardson/react-primitives#134]
```
/Users/brodybits/dev/react-primitives/src/injection/react-native-web.js
  22:38  error  Unable to resolve path to module 'react-native-web/dist/cjs/exports/StyleSheet/createStyleResolver'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)
```

Seems to be due to the second commit (c757e59c530277a2ac46966318bd193ad0fcaf19) in PR #130.

Seems to lead to lint errors on Travis CI.

Same recommended solution to both #131 and this issue: revert c757e59c530277a2ac46966318bd193ad0fcaf19, require RNW 0.11(+) in peerDependencies, and bump the 0.x version.

**Comment by mathieudutour** [comment]
fixed in https://github.com/lelandrichardson/react-primitives/commit/7d8e6b4aaa4be6229f89e9b6993ae1adda18653b
