### ISSUE TITLE
New platform proposal: React Figma

### ISSUE THREAD

**Issue by macintoshhelper** [lelandrichardson/react-primitives#142]
Hi, I've created a fork of `react-primitives` at https://github.com/elemental-design/react-primitives/tree/feat/figma-platform

This adds a new platform target: `react-figma`, that has a common API surface with `react-native`/`react-sketchapp`.

This will allow `react-figma` to support `styled-components/primitives`.

Should I go ahead and submit a PR, and should there be a larger discussion around adding new platforms (e.g. `react-pdf`, etc)?

@mathieudutour

**Comment by mathieudutour** [comment]
As long as it’s the same API, I’m all for it 👍
