### ISSUE TITLE
Support for ul, buttons, icons?

### ISSUE THREAD

**Issue by priley86** [lelandrichardson/react-primitives#60]
I'm new to this library, but would like to explore it alongside React Sketchapp for my designs & React web applications. 

After playing w/ the examples in Sketch App, it looks like we have support for the following via primitives:

View -> renders `div` 
Image -> renders `img`
Text -> renders `span`

Is there a suggested practice for rendering other web element types? I guess a few that come to mind immediately are some already mentioned I believe...

`ul` for lists
`button` for buttons
`i` for icons
`input` for inputs

It would be nice to have a doc detailing what the recommended primitives are for each element type...

Thanks so much for all your hard work on this. This is amazing!!!

**Comment by necolas** [comment]
The docs for react-native-web explain how to use the React Native accessibility props to render specific Dom elements

**Comment by priley86** [comment]
ok - this is good to know that you'll be following that project's conventions. I'll stay tuned there as well. ;)

Closing this issue...
