### ISSUE TITLE
Differences between sketch and web: misaligned flex boxes

### ISSUE THREAD

**Issue by jlongster** [lelandrichardson/react-primitives#61]
I'm rendering rows that all have equal width cells using `flex: 1`. The problem is on the web, if the cell has content, the width is not the same as the cells in other rows and it becomes misaligned. Full code to reproduce is here:

```js
import React from 'react';
import { Text, View } from 'react-primitives';

function Row({ children }) {
  return (
    <View style={{ flexDirection: 'row', height: 50 }}>
      <View style={{ borderWidth: 1, borderColor: '#f0f0f0', flex: 1 }} />
      <View style={{ borderWidth: 1, borderColor: '#f0f0f0', flex: 1 }}>
        {children}
      </View>
      <View style={{ borderWidth: 1, borderColor: '#f0f0f0', flex: 1 }} />
      <View style={{ borderWidth: 1, borderColor: '#f0f0f0', flex: 1 }} />
    </View>
  );
}

function Document() {
  return (
    <View style={{ width: 500 }}>
      <Row>hello</Row>
      <Row />
      <Row />
      <Row />
      <Row />
    </View>
  );
}

export default Document;
```

If you render this in sketch it looks like this, which is correct:

<img width="845" alt="screen shot 2017-05-15 at 12 27 14 pm" src="https://cloud.githubusercontent.com/assets/17031/26067974/dbb20db0-3969-11e7-93d5-617f86759faf.png">

However, rendering on the web shows this:

<img width="651" alt="screen shot 2017-05-15 at 12 27 48 pm" src="https://cloud.githubusercontent.com/assets/17031/26067997/ede69a64-3969-11e7-89e3-a4695c3455cd.png">

It's clearly a difference in how flex is treated, but I'd like to know why and if there's any way react-primitives can make it more consistent.

**Comment by andrewgrewell** [comment]
Just a shot in the dark here, but it looks like a padding / margin issue. Have you tried setting padding and margin to 0 on the text element

**Comment by jlongster** [comment]
@andrewgrewell No difference, but I don't think it's a padding issue. It's a flex behavior that I don't understand. As far as I know the sketch layout is how it should look since the content does not overflow.

**Comment by jlongster** [comment]
Ugh if I set `flex-basis: 0` it seems to line up. Now to figure out where to fix this.

**Comment by andrewgrewell** [comment]
I noticed in the web implementation of `View` there is this comment :
```
// TODO(lmr):
// we should probably ensure that children is not a string, and enforce that those types of
// children be rendered in a `<Text>` component
```
So maybe try wrapping 'hello' in a `Text`

**Comment by jlongster** [comment]
Yeah I realized that forget `Text`, but these are all red herrings.

If I explicitly set `flexBasis: 0` it works. I think this is a bug in react-sketchapp's implementation of flex so I'll file there.

**Comment by jlongster** [comment]
https://github.com/airbnb/react-sketchapp/issues/98

**Comment by necolas** [comment]
This was a bug in react-native-web: https://github.com/necolas/react-native-web/commit/88ddeca0c6b8ad8f2f690e07cd4ede7f9a31d1e2
