### ISSUE TITLE
extract css from SylesSheet to separate css file

### ISSUE THREAD

**Issue by dominikchrastek** [lelandrichardson/react-primitives#64]
Hello,
is there some way how to extract css from SylesSheet to separate css file?
When I have server side rendering, it looks weird when the component is missing styles for a while.

**Comment by MoOx** [comment]
```js
import { StyleSheet } from "react-primitives"

StyleSheet.renderToString() // return styles
```

Comes from react-native-web.

**Comment by sergiodxa** [comment]
I tried using `renderToString` and doesn't exists that method, instead I used `StyleSheet.getStyleSheets` who returns and array of object with an ID and textContent (the styles)

**Comment by episodeyang** [comment]
The `StyleSheet.getStyleSheets` doesn't work when I tried it

**Comment by episodeyang** [comment]
@sergiodxa Thanks! `StyleSheet.getStyleSheets` works:

```javascript
const html = renderToString(
        <StaticRouter location={location} context={{}}>
            <Root/>
        </StaticRouter>
    );
    const css = StyleSheet
        .getStyleSheets()
        .map(({id, textContent}) => `<style id=${id}>${textContent}</style>`)
        .join('');
    res.status(200).send(
        HTML
            .replace(/<!-- SSR:CSS -->/, css)
            .replace(/<!-- SSR:HTML -->/, html)
```
