### ISSUE TITLE
<Touchable /> is broken (Native)

### ISSUE THREAD

**Issue by amaldare93** [lelandrichardson/react-primitives#71]
I cant render any `Touchable` elements in react-native (using `react-primitives` or `styled-components/primitives` 

looks like this is the same issue as https://github.com/airbnb/react-sketchapp/issues/104

Code:
```js
import React from 'react'
import { Touchable } from 'react-primitives'
export default () => <Touchable />
```

Versions:
```js
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
"react-primitives": "^0.4.3",
"styled-components": "^2.1.0"
```

Error: 
![image](https://user-images.githubusercontent.com/5483462/27778029-eb80e72e-5f85-11e7-8b24-f32f87d4babc.png)

**Comment by necolas** [comment]
React 16 isn't supported yet

**Comment by amaldare93** [comment]
I thought it might have something to do with that, but thats the version that `react-native init` gives you (idk why they would do that).

Downgrading react isnt going to be easy because all the other peer dependencies of react v16, but im trying.

This is my first time dealing with incompatible dependencies.

**Comment by ktj** [comment]
I have this same issue and I'm using react 15.4.x and react-native 0.42.x.

The problem is that in Touchable.js Touchable class there is no such function.

**Comment by ktj** [comment]
@amaldare93 
This helps in downgrading:
https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md

**Comment by samjt** [comment]
I'm also having the same issue, tried initially with 
- React @16.0.x
- React-Native @0.45.x
- React-Primitives @0.4.3

I then reverted to:

- "react": "^15.4.1",
- "react-dom": "^15.6.1",
- "react-native": "^0.42",
- "react-primitives": "^0.4.3"

as @ktj says

**Comment by vincentmvdm** [comment]
Are there plans to make Touchable work with React 16? Currently getting the same issue with React 16 & CRNA.

**Comment by likethemammal** [comment]
Made a PR for React 16 here: https://github.com/lelandrichardson/react-primitives/pull/98

**Comment by Hermanya** [comment]
I'm still getting this error
```
    "exp": "^49.1.0",
    "expo": "^25.0.0",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-web": "^0.3.2",
    "react-primitives": "^0.5.0",
    "react-primitives-svg": "^0.0.3",
    "react-scripts": "1.1.0",
    "react-sketchapp": "^1.0.0",
    "react-test-renderer": "^16.2.0"
```
At first I suspected that my react-native is not up to date, but expo's react native 25.0.0 released 18 days ago.
