### ISSUE TITLE
StyleRegistry import is broken for web (react-native-web) since v0.0.100

### ISSUE THREAD

**Issue by MoOx** [lelandrichardson/react-primitives#72]
This commit https://github.com/necolas/react-native-web/commit/43d297bf5963791b191223262cf7ed370c345a0a is changing some imports.
So now this https://github.com/lelandrichardson/react-primitives/blob/39fcd34fcffac7403494f832e0bac3136ca05ad0/src/injection/react-native-web.js#L13 is broken.

I will try to push a fix asap.

**Comment by necolas** [comment]
Why is `resolve` being added to the `StyleSheet` export anyway?

**Comment by MoOx** [comment]
`resolve` can be handy when you play with the limite of react-primitives and wants to make a custom component (web in my case).
Are you open for a PR to RNW to add it like you [mentioned](https://github.com/lelandrichardson/react-primitives/pull/73#discussion_r125895021)?

**Comment by necolas** [comment]
is there anything you can't do with `createElement` + `StyleSheet`?

**Comment by MoOx** [comment]
I guess so. I initially wanted to use react-primitives directly the project is probably not mature enough. Will go back to RNW directly.

**Comment by MoOx** [comment]
I guess so. I initially wanted to use react-primitives directly but the project is probably not mature enough. Will go back to RNW directly.

**Comment by necolas** [comment]
Oh I see. Yeah I'm not sure if primitives should augment StyleSheet. If you need to do custom web stuff it's probably best to switch over to RNW, as you would RN for custom native. But hopefully this is something we'll all figure out as we go

**Comment by mathieudutour** [comment]
fixed in v0.5.0
