### ISSUE TITLE
Number of classes generated

### ISSUE THREAD

**Issue by dominicfallows** [lelandrichardson/react-primitives#74]
This is more of a question, and request for information, rather than a specific issue - however in terms of development maintenance and code readability you could class it as an issue. 

I have created a component using react-primitives, comprising some common elements. 

`<Touchable onPress={() => console.log("Button Press")}>
      <View style={styles.button}>
        <View style={styles.icon}></View>
        <Text style={styles.label}>{label}</Text>
      </View>
    </Touchable>`

All works great, react-primitives library is great. 

My question/query is - what is the need for so many generated classes? 

For example, in development workflow the classes great in number: 
![react-primitives-component-classes-development](https://pbs.twimg.com/media/DEDmmqWWsAEl3zr.jpg)

Even in a production build, the number of classes is great:
![react-primitives-component-classes-production](https://pbs.twimg.com/media/DEDmmqUXUAAk5uK.jpg)

As I said, it's not necessarily a bug, it *could* be considered an issue in terms of development maintenance and code readability. I'm more asking for opinions and advice (if there is a way to optimise further). 

Thanks in advance.

**Comment by necolas** [comment]
See https://github.com/necolas/react-native-web/blob/master/docs/guides/style.md, and rely on React Dev Tools to edit styles

**Comment by dominicfallows** [comment]
Perfect, thanks.... *always read the instructions* 

![always read the instructions](https://pbs.twimg.com/media/DEDopE-XsAE6Ob0.jpg)

**Comment by albertoblaz** [comment]
Sorry but I didn't find the answer to this question: 

> what is the need for so many generated classes?

Or better said: Will this library generate a clean HTML output without all those classnames?

Besides this, I've tried react-primitives and it looks like an awesome project!!. I'm so looking forward to trying it in our company and create universal components that we can easily import in React Sketch. The problem is that our app is a bit too heavy, so if we use this, our HTML will be humongous :(

**Comment by MoOx** [comment]
In short: it has been made for perfs. https://github.com/necolas/react-native-web/issues/307
