### ISSUE TITLE
react-primitives is not transpiling when bundling for react-native production

### ISSUE THREAD

**Issue by peterp** [lelandrichardson/react-primitives#79]
In my react-native project

```terminal
node ./node_modules/react-native/local-cli/cli.js bundle --entry-file index.ios.js --platform ios --dev false --reset-cache --bundle-output /tmp/main.jsbundle --assets-dest /tmp/
```

```terminal
**TypeError: /Users/peterp/Personal/xxx/node_modules/react-primitives/lib/modules/Platform.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "StringLiteral"**
transform[stderr]:     at Object.validate (/Users/peterp/Personal/xxx/node_modules/babel-types/lib/definitions/index.js:109:13)
transform[stderr]:     at Object.validate (/Users/peterp/Personal/xxx/node_modules/babel-types/lib/index.js:505:9)
transform[stderr]:     at NodePath._replaceWith (/Users/peterp/Personal/xxx/node_modules/babel-traverse/lib/path/replacement.js:176:7)
transform[stderr]:     at NodePath.replaceWith (/Users/peterp/Personal/xxx/node_modules/babel-traverse/lib/path/replacement.js:160:8)
transform[stderr]:     at PluginPass.MemberExpression (/Users/peterp/Personal/xxx/node_modules/metro-bundler/build/JSTransformer/worker/inline.js:126:14)
```

I've narrowed it down the assignment here: https://github.com/lelandrichardson/react-primitives/blob/master/src/modules/Platform.js#L13

**Comment by peterp** [comment]
I changed line 13-14 to
 
```javascript
    Platform['OS'] = platform.OS;
    Platform['Version'] = platform.Version;
```

and it built successfully, this [comment](https://github.com/facebook/react-native/issues/7607#issuecomment-221425153) helped me figure it out.

**Comment by blargity** [comment]
We're having this issue too, but unfortunately the fix above doesn't seem to work for us.

We had to remove `react-primitives` from our project and instead use React Native versions from our project to get release builds to work on React Native. :-(

**Comment by peterp** [comment]
@blargity I've created a very hacky release that you could test: `npm install peterp/react-primitives`

**Comment by blargity** [comment]
That's ok, I'll keep an eye on this issue for an official fix. We'll be able to switch back really easily. Thanks though!

**Comment by necolas** [comment]
You can also alias react-native to react-native-web if you're having problems

**Comment by peterp** [comment]
@necolas that sounds interesting, how would one go about doing that?

**Comment by necolas** [comment]
https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md

**Comment by samjt** [comment]
@peterp What fixes did you end up implementing? I can't find your repo and the 'string' accessor fix doesn't seem to work

**Comment by jevakallio** [comment]
Note, the string accessor fix works for me when applied to `lib/modules/Platform.js` (note `lib`, not `src` as linked by @peterp's original post. The `index.js` imports directly from lib.) 

If you want the change to be patched in permanently until this gets fixed, I can recommend [patch-package](https://github.com/ds300/patch-package).

1. Replace the dot notation property access with brackets in `lib/modules/Platform.js` (and in src as well, if you want to be cool about it):
```diff
-    Platform.OS = platform.OS;
-    Platform.OS = platform.Version;
+    Platform['OS'] = platform.OS;
+    Platform['Version'] = platform.Version;
```

2. Install patch-package with `npm install --dev patch-package`.
3. Add `prepare` npm script:
```
scripts: {
  //snip...
  "prepare": "patch-package"
}
```
4. Run `patch-package` to generate patch:
```sh
npm run prepare -- react-primitives
```
5. Commit the created `patches/` folder to source control.

The patch should now be applied every time you `npm install` or `yarn`

**Comment by jevakallio** [comment]
@peterp @lelandrichardson I know this is an issue that should really be fixed in metro-bundler, but for the time being (and for backwards compatibility for existing versions of Metro going forward) I think the fix should be upstreamed to `react-primitives`.

Is there a reason you didn't create a PR for this? I can go ahead and do that, just wanted to check if this is something you've already thought through and considered a bad idea?

**Comment by peterp** [comment]
@jevakallio I've already reported the issue to the metro-bundler team: https://github.com/facebook/metro-bundler/issues/27

I agree that this _could_ be fixed here, but I don't know if it would be merged, since the touchable and stylesheet pull-requests have been open for almost 2 months. Certainly that isn't a good attitude to have on my part, but I need a fix almost immediately and opted for alias approach instead of a injection package.

**Comment by jevakallio** [comment]
I submitted a PR for it in Metro, let's see how that goes https://github.com/facebook/metro-bundler/pull/45

**Comment by sibelius** [comment]
I think we can close this
