### ISSUE TITLE
react-native-web vs react-web

### ISSUE THREAD

**Issue by L1fescape** [lelandrichardson/react-primitives#80]
I noticed [pseudo-selectors and media-queries](https://github.com/lelandrichardson/react-primitives/tree/39fcd34fcffac7403494f832e0bac3136ca05ad0/src/web/StyleSheet/registry.js#L78-L93) are implemented in the `StyleSheet` defined in `src/web/`, however trying to use a pseudo-selector the [same way they're used in tests](https://github.com/lelandrichardson/react-primitives/tree/39fcd34fcffac7403494f832e0bac3136ca05ad0/src/web/StyleSheet/__tests__/StyleSheet-tests.js#L14-L19) leads to the following error:

```
Warning: ":hover" is not a valid style property.
StyleSheet body: {
  "width": 30,
  ":hover": {
    "width": 20
  }
}
```

This is because the `StyleSheet` object being imported on web is the one from [`react-native-web`](https://github.com/necolas/react-native-web/blob/02cfbf8987ce3a3f4675dcf4d8904ba2492092fa/src/apis/StyleSheet/StyleSheetValidation.js#L30), which does not implement pseudo-selectors. So that leads me to my question: what's the the story behind `react-web` and what are your plans for it?

This is a sweet project and it was awesome meeting you at Chain React!

**Comment by mathieudutour** [comment]
the `src/web` is from before `react-native-web` existed. It's not used anymore
