### ISSUE TITLE
TypeScript Definitions Missing

### ISSUE THREAD

**Issue by AlexLeung** [lelandrichardson/react-primitives#82]
Currently I can't compile my typescript react project when trying to use the new `styled-components/primitives` library extension because typings definitions are not present for the `react-primitives` repository. There is also no `@types/react-primitives` present either.

**Comment by fiber-god** [comment]
+1

**Comment by ljharb** [comment]
A PR to @types probably makes the most sense; airbnb doesn't use TypeScript.

**Comment by andrespch** [comment]
Any updates on this? did you solve this somehow @AlexLeung  @fiber-god ?

**Comment by AlexLeung** [comment]
Haven’t had time to write the definitions

**Comment by mathieudutour** [comment]
The definitions shouldn't be too hard to write, it's basically a subset of the `react-native` types. You even probably import the types from `react-native` directly

**Comment by awfulaxolotl** [comment]
As @mathieudutour suggested, you can import the types from `@types/react-native`.

I got it working by making a `src/@types/react-primitives/index.d.ts` file with the following contents:

```ts
declare module 'react-primitives' {
  export {
    StyleSheet,
    View,
    Text,
    Image,
    Touchable,
    Animated,
  } from 'react-native'
}
```

There will be one more step if you're using React Primitives in a Webpack build. Webpack and React Native both declare global, incompatible type definitions for `require`.

So you'll have add the following to your `tsconfig.json` to just avoid type-checking `node_modules` (which is faster anyways):

```js
{
  "compilerOptions": {
    // Required for using `react-primitives` types, but
    // also makes typechecking faster in general.
    //
    // The problem actually stems from this project using
    // `@types/react-native` to fake types for `react-primitives`.
    // React Native and Webpack both define a global `require`
    // differently, so there's a conflict.
    "skipLibCheck": true,
  }
}
```

Hopefully that helps!

I would normally make a PR to this repo or DefinitelyTyped to just add these, but I'm not familiar enough with React Native and Primitives to know if it's truly a one-to-one types match. Can someone more in-the-know help with that?

**Comment by johnnyBira** [comment]
I tried this with `react-dom` and I'm getting a bunch of type errors.

This is my super basic component:
```javascript
import * as React from 'react';
import styled from 'styled-components/primitives'

const StyledParent = styled.View`
  background: red;
  padding: 10px;
`;

const StyledChild = styled.View`
  width: 10px;
  height: 10px;
  background: green;
`;

class Button extends React.Component<any, any> {
  public render() {
    return (
      <div>
        <StyledParent>
          <StyledChild />
        </StyledParent>
      </div>
    )
  }
}

export default Button;
```

And these are the errors:
ERROR in [at-loader] ./src/Button.tsx:19:10 
    TS2322: Type '{ children: Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<View, any>, Compo...'.
  Type '{ children: Element; }' is not assignable to type 'Readonly<ThemedOuterStyledProps<View, any>>'.
    Property 'measure' is missing in type '{ children: Element; }'.
ERROR in [at-loader] ./src/Button.tsx:20:12 
    TS2322: Type '{}' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<View, any>, Compo...'.
  Type '{}' is not assignable to type 'Readonly<ThemedOuterStyledProps<View, any>>'.
    Property 'measure' is missing in type '{}'.

**Comment by brunolemos** [comment]
Someone posted a similar code from above on `DefinitelyTyped` so you can do this now: `yarn add --dev @types/react-primitives`.

**Comment by earksiinni** [comment]
I've installed `@types/react-primitives` but I'm still getting this error. Do I need to add some line of code to map the import statement to the declaration file?
