### ISSUE TITLE
Animated.View appears to load another version of React.

### ISSUE THREAD

**Issue by robertgonzales** [lelandrichardson/react-primitives#85]
I'm using `react-primitives` in a standalone react library. However, I'm unable to import and use the library components in another app since any component that uses `Animated.View` causes this error to show up:
```
Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. 
You might be adding a ref to a component that was not created inside a component's `render` method, 
or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

Note: other components seem to work fine: if I replace `Animated.View` with `View` the error resolves.

**Comment by ktj** [comment]
https://github.com/necolas/react-native-web/issues/599

**Comment by robertgonzales** [comment]
Oops, forgot to close the issue. Thanks!
