### ISSUE TITLE
Clarify differences between `react-primitives` and `reactxp`

### ISSUE THREAD

**Issue by jferrettiboke** [lelandrichardson/react-primitives#88]
[ReactXP](https://github.com/Microsoft/reactxp) is a library for cross-platform app development using React and React Native, such as Web, Android, iOS, Windows 10 and it seems that they recently added support for macOS.

My first impression was that both of them are pretty similar because they are libraries cross-platform for building apps. I read a little bit more about them and I think the main differences between them are that `react-primitives` is focused on building just the interface across targets while `reactxp` is focused on cross-platform app development with all the app logic included. And, of course, the targets/platforms between them are not the same at this point in time.

I would like that someone could clarify this more to have a better understanding and tell me if I am right or wrong. I would appreciate it because, maybe, the differences between them are bigger that I expected them.

Thanks for this amazing library!

**Comment by bogdansoare** [comment]
Good question. Also what is the difference between *react-primitives* and *react-native-web* ?

**Comment by MoOx** [comment]
-web is for the... web. -primitives is (in theory) for multiples platforms (like sketch) following react-native APIs.

**Comment by mathieudutour** [comment]
Yeah you are right, they are pretty similar, I'd say the goal is the same but the supported platforms and APIs are different. `react-primitives` was open sourced as a mean to bring the community to discuss those subjects and implement a solution while `ReactXP` arrived a bit later as a "ready-to-use" framework used by Microsoft
