### ISSUE TITLE
Looking for a basic example

### ISSUE THREAD

**Issue by thebetterjort** [lelandrichardson/react-primitives#89]
Anybody have a basic example?  The example/ folder is an example, but its much too difficult for me to understand all the working parts.
I'm wondering if I can use create-react-app & create-reactnative-app w/ styled-components and primitives to create a universal component system. eg) Rendering a H1 on android, web, ios would be very helpful.
Thanks.

**Comment by ktj** [comment]
with styled components:
```
import styled from 'styled-components/primitives';

export const H1 = styled.Text`
  font-size: 48px;
`;
```

**Comment by thebetterjort** [comment]
In terms of directory structure and business logic.

app/
--/ios
--/android
--/web

Are people writing components 3 different times for 3 different files (platforms)? Or is there sometype of check that can be made to ensure the proper codes gets run?

**Comment by jferrettiboke** [comment]
[Watch this](https://youtu.be/hNwQPJy-XZY?t=15m53s) in order to clarify yourself a little bit more. It was suggested by @lelandrichardson.
